# Common Labels
labels:
  app: "health-registration-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "health-registration-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "health_registration_service_schema"
    image:
      repository: "health-registration-service-db"

# Container Configs
image:
  repository: "health-registration-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health-registration-service/health"
  readinessProbePath: "/health-registration-service/health"
appType: "java-spring"
tracing-enabled: true
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/digit-health-registration-service-persister.yml"
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-registration-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}