# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/health-dev\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:680148267093:key/854210b1-3f8e-4176-b4ae-d728a467970b'
